// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jezikmzmojbpwdgizahb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplemlrbXptb2picHdkZ2l6YWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTMwMzgsImV4cCI6MjA2NTA4OTAzOH0.HcNbS6_29HxtcsW9vfoUNLENNwmv2Y0x0oBQ0DUYO1k";

// Debug log for environment variables
console.log('🔧 Supabase Config:', {
  url: SUPABASE_URL,
  key: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...',
  hasEnvUrl: !!import.meta.env.VITE_SUPABASE_URL,
  hasEnvKey: !!import.meta.env.VITE_SUPABASE_ANON_KEY
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);